### PR TITLE
refer to access-your-VM from customize-vm-network for hostnames

### PR DESCRIPTION
**Pull request by larsmans**
It took me an email to @schot to figure out where hostnames are described; I expected to find them in the network docs, so I linked from those to where they are described.

### CODE REVIEW

**Comment by niekbosch** [comment]
Lijkt mij prima

**Comment by schot** [comment]
+1
We can even point  the link to the right header (#find-ip-address-or-host-name), but in the current layout this will hide the header pointed to.

**Comment by larsmans** [comment]
My main concern was landing on a page where <kbd>Ctrl</kbd>+<kbd>F</kbd> "hostname" works :)

**Comment by niekbosch** [comment]
We still have to look at the layout indeed. But that will come.

Hey, I can make an issue out of that now!

**Pull request merged**
